import type { FeedSourceDefinition } from "../types";

export const DEFAULT_FEEDS: FeedSourceDefinition[] = [
  {
    id: "decentralised",
    url: "https://www.decentralised.co/feed",
    source: "Decentralised.co",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "ournetwork",
    url: "https://www.ournetwork.xyz/",
    source: "OurNetwork",
    type: "html",
    category: "Crypto",
    parserKey: "ournetwork",
  },
  {
    id: "shoal",
    url: "https://www.shoal.gg/feed",
    source: "Shoal",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "artemis",
    url: "https://research.artemisanalytics.com/feed",
    source: "Artemis",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "ethereum-foundation",
    url: "https://blog.ethereum.org/feed.xml",
    source: "Ethereum Foundation",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "celestia",
    url: "https://blog.celestia.org/rss/",
    source: "Celestia",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "arbitrum-foundation",
    url: "https://blog.arbitrum.foundation/rss/",
    source: "Arbitrum Foundation",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "arbitrum-tech",
    url: "https://blog.arbitrum.io/rss/",
    source: "Arbitrum Tech",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "starkware",
    url: "https://medium.com/feed/starkware",
    source: "StarkWare",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "aave",
    url: "https://medium.com/feed/aave",
    source: "Aave",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "compound",
    url: "https://medium.com/feed/compound-finance",
    source: "Compound",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "1inch",
    url: "https://medium.com/feed/1inch-network",
    source: "1inch",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "chainlink",
    url: "https://blog.chain.link/rss/",
    source: "Chainlink",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "flashbots",
    url: "https://medium.com/feed/flashbots",
    source: "Flashbots",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "blockworks",
    url: "https://blockworks.co/feed",
    source: "Blockworks",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "coindesk",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    source: "CoinDesk",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "unchained",
    url: "https://unchainedcrypto.com/feed/",
    source: "Unchained",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "vitalik",
    url: "https://vitalik.eth.limo/feed.xml",
    source: "Vitalik",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "castle-labs",
    url: "https://castlelabs.substack.com/feed",
    source: "Castle Labs",
    type: "rss",
    category: "Crypto",
  },
  {
    id: "april-dunford",
    url: "https://aprildunford.substack.com/feed",
    source: "April Dunford",
    type: "rss",
    category: "Marketing",
  },
  {
    id: "mkt1",
    url: "https://newsletter.mkt1.co/feed",
    source: "MKT1",
    type: "rss",
    category: "Marketing",
  },
];
